/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CA1project;

import javax.swing.JOptionPane;

/**
 *
 * Name: Nerijus Kmitas
 * StudentID: x24170232
 * 
 */
public class ParkingGUI extends javax.swing.JFrame {
    
    //Data structure
    private SinglyLinkedList bookingList = new SinglyLinkedList();
    private StackADT actionStack = new StackADT();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParkingGUI.class.getName());

    /**
     * Creates new form ParkingGUI
     */
    public ParkingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        vehicleIDLabel = new javax.swing.JLabel();
        ownerNameLabel = new javax.swing.JLabel();
        vehicleTypeLabel = new javax.swing.JLabel();
        bookingIDLabel = new javax.swing.JLabel();
        parkingAreaLabel = new javax.swing.JLabel();
        addBookingButton = new javax.swing.JButton();
        deleteBookingButton = new javax.swing.JButton();
        viewAllBookingsButton = new javax.swing.JButton();
        undoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayOutputTextArea = new javax.swing.JTextArea();
        vehicleIDTextField = new javax.swing.JTextField();
        ownerNameTextField = new javax.swing.JTextField();
        vehicleTypeTextField = new javax.swing.JTextField();
        bookingIDTextField = new javax.swing.JTextField();
        parkingAreaTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Smart Parking App");

        vehicleIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleIDLabel.setText("Vehicle ID");

        ownerNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ownerNameLabel.setText("Owner Name");

        vehicleTypeLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleTypeLabel.setText("Vehicle Type");

        bookingIDLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bookingIDLabel.setText("Booking ID");

        parkingAreaLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        parkingAreaLabel.setText("Parking Area");

        addBookingButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBookingButton.setText("Add Booking");
        addBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookingButtonActionPerformed(evt);
            }
        });

        deleteBookingButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBookingButton.setText("Delete Booking");
        deleteBookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookingButtonActionPerformed(evt);
            }
        });

        viewAllBookingsButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewAllBookingsButton.setText("View All");
        viewAllBookingsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllBookingsButtonActionPerformed(evt);
            }
        });

        undoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        undoButton.setText("Undo");
        undoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoButtonActionPerformed(evt);
            }
        });

        displayOutputTextArea.setColumns(20);
        displayOutputTextArea.setRows(5);
        jScrollPane1.setViewportView(displayOutputTextArea);

        vehicleIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleIDTextFieldActionPerformed(evt);
            }
        });

        ownerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ownerNameTextFieldActionPerformed(evt);
            }
        });

        vehicleTypeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleTypeTextFieldActionPerformed(evt);
            }
        });

        bookingIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingIDTextFieldActionPerformed(evt);
            }
        });

        parkingAreaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parkingAreaTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(deleteBookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(viewAllBookingsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(undoButton, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vehicleIDLabel)
                            .addComponent(ownerNameLabel)
                            .addComponent(vehicleTypeLabel)
                            .addComponent(bookingIDLabel)
                            .addComponent(parkingAreaLabel))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vehicleIDTextField)
                            .addComponent(ownerNameTextField)
                            .addComponent(vehicleTypeTextField)
                            .addComponent(bookingIDTextField)
                            .addComponent(parkingAreaTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleLabel)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleIDLabel)
                    .addComponent(vehicleIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ownerNameLabel)
                    .addComponent(ownerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleTypeLabel)
                    .addComponent(vehicleTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bookingIDLabel)
                    .addComponent(bookingIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(parkingAreaLabel)
                    .addComponent(parkingAreaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBookingButton)
                    .addComponent(deleteBookingButton)
                    .addComponent(viewAllBookingsButton)
                    .addComponent(undoButton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicleIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleIDTextFieldActionPerformed
        // TODO add your handling code here:
        int vehicleID;
        
        try {
            vehicleID = Integer.parseInt(vehicleIDTextField.getText());
            
            if(vehicleID <= 0) {
                JOptionPane.showMessageDialog(this, "Vehicle ID must be an integer number");
                return;
            }
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vehicle ID must be an integer");
            return;
        }
    }//GEN-LAST:event_vehicleIDTextFieldActionPerformed

    private void addBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookingButtonActionPerformed
        // TODO add your handling code here:
        int vehicleID;
        int bookingID;
        
        String owner = ownerNameTextField.getText().trim();
        String type = vehicleTypeTextField.getText().trim();
        String parkingArea = parkingAreaTextField.getText().trim();
        
        //Validation of vehicle ID
        try {
            vehicleID = Integer.parseInt(vehicleIDTextField.getText());
            
            if(vehicleID <= 0) {
                JOptionPane.showMessageDialog(this, " Vehicle ID cannot be empty");
                return;
            }
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Vehicle Id must be an Integer number");
            return;
        }
        
        //Validation of Owner name
        if(owner.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Owner Name cannot be empty");
            return;
        }
        if(!owner.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Owner Name must contain only letters");
            return;
        }
        
        //Validation of vehicle Type
        if(type.isEmpty() || !type.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Vehicle Type must contain only letters");
            return;
        }
        
        //Validation of a booking ID
        try {
            bookingID = Integer.parseInt(bookingIDTextField.getText());
            
            if(bookingID <= 0) {
                JOptionPane.showMessageDialog(this, "Booking ID cannot be empty");
                return;
            }
        }
        catch(NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Booking ID must be an Integer number");
                return;
        }
        
        //Validation of parking Area
        if(parkingArea.isEmpty() || !parkingArea.matches("[a-zA-Z0-9]+")) {
            JOptionPane.showMessageDialog(this, "Parking Area cannot be empty. Example: (A1, B2, C1 etc.)");
            return;
        }
        
        //Creating objects
        Vehicle v;
        if(type.equalsIgnoreCase("Car")) {
            v = new Car(vehicleID, owner, 4);
        }
        else if(type.equalsIgnoreCase("Bike")) {
            v = new Bike(vehicleID, owner, true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Vehicle Type must be Car or Bike");
            return;
        }
        Booking b = new Booking(bookingID, parkingArea, v);
        
        bookingList.create(b);
        actionStack.push("Add Booking");
        
        displayOutputTextArea.setText("Booking Added Successfully!");
        
        vehicleIDTextField.setText("");
        ownerNameTextField.setText("");
        vehicleTypeTextField.setText("");
        bookingIDTextField.setText("");
        parkingAreaTextField.setText("");
    }//GEN-LAST:event_addBookingButtonActionPerformed

    private void deleteBookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookingButtonActionPerformed
        // TODO add your handling code here:
        try {
            int bookingID = Integer.parseInt(bookingIDTextField.getText());
            
            bookingList.delete(bookingID);
            actionStack.push("Delete Booking");
            
            displayOutputTextArea.setText("Booking Deleted");
        }
        catch (Exception e) {
            displayOutputTextArea.setText("Enter valid Booking ID");
            
        }
    }//GEN-LAST:event_deleteBookingButtonActionPerformed

    private void viewAllBookingsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllBookingsButtonActionPerformed
        // TODO add your handling code here:
        displayOutputTextArea.setText("");
        
        Node temp = bookingList.getHead();
        
        while(temp != null) {
            displayOutputTextArea.append(temp.data.toString() + "\n");
            
            temp = temp.next;
        }
    }//GEN-LAST:event_viewAllBookingsButtonActionPerformed

    private void undoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoButtonActionPerformed
        // TODO add your handling code here:
        String lastAction = actionStack.pop();
        
        if(lastAction != null) {
            displayOutputTextArea.setText("Undo: " + lastAction);
        }
        else {
            displayOutputTextArea.setText("Nothing to undo");
        }
    }//GEN-LAST:event_undoButtonActionPerformed

    private void ownerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ownerNameTextFieldActionPerformed
        // TODO add your handling code here:
        String owner = ownerNameTextField.getText().trim();
        
        if(owner.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Owner Name cannot be empty");
            return;
        }
        if(!owner.matches("[a-zA-Z ]+")) {
            JOptionPane.showMessageDialog(this, "Owner Name must contain only letters");
            return;
        }
    }//GEN-LAST:event_ownerNameTextFieldActionPerformed

    private void vehicleTypeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleTypeTextFieldActionPerformed
        // TODO add your handling code here:
        String type = vehicleTypeTextField.getText().trim();
        
        if(type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vehicle Type cannot be empty");
            return;
        }
        if(!type.matches("[a-zA-Z]+")) {
            JOptionPane.showMessageDialog(this, "Vehicle Type must contain only letters");
            return;
        }
    }//GEN-LAST:event_vehicleTypeTextFieldActionPerformed

    private void bookingIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingIDTextFieldActionPerformed
        // TODO add your handling code here:
        int bookingID;
        
        try{
            bookingID = Integer.parseInt(bookingIDTextField.getText());
            
            if(bookingID <= 0) {
            JOptionPane.showMessageDialog(this, "Booking ID must be an integer");
            return;
            }
        }
        catch(NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Booking ID must be an integer number");
            return;
        }
    }//GEN-LAST:event_bookingIDTextFieldActionPerformed

    private void parkingAreaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parkingAreaTextFieldActionPerformed
        // TODO add your handling code here:
        String parkingArea = parkingAreaTextField.getText().trim();
        
        if(parkingArea.isEmpty() || !parkingArea.matches("[a-zA-Z0-9]+")) {
            JOptionPane.showMessageDialog(this, "Parking Area cannot be empty");
            return;
        }
        if(!parkingArea.matches("[a-zA-Z0-9]+")) {
            JOptionPane.showMessageDialog(this, "Parking Area must contain only letters");
            return;
        }
    }//GEN-LAST:event_parkingAreaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ParkingGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBookingButton;
    private javax.swing.JLabel bookingIDLabel;
    private javax.swing.JTextField bookingIDTextField;
    private javax.swing.JButton deleteBookingButton;
    private javax.swing.JTextArea displayOutputTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel ownerNameLabel;
    private javax.swing.JTextField ownerNameTextField;
    private javax.swing.JLabel parkingAreaLabel;
    private javax.swing.JTextField parkingAreaTextField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton undoButton;
    private javax.swing.JLabel vehicleIDLabel;
    private javax.swing.JTextField vehicleIDTextField;
    private javax.swing.JLabel vehicleTypeLabel;
    private javax.swing.JTextField vehicleTypeTextField;
    private javax.swing.JButton viewAllBookingsButton;
    // End of variables declaration//GEN-END:variables
}
